### ISSUE TITLE
Library misses some important functions without math3d.

### ISSUE THREAD

**Issue by NikolasE** [SintefManufacturing/python-urx#24]
Hey!

Thanks a lot for making the interface commercially usable by changing the license to LGPL. Math3d (GPL) is however needed, even for basic functions like get_pose. Is there a plan to improve the LGPL-parts?

**Comment by oroulet** [comment]
The author of math3d loves GPL and wants to keep licence. If you know an lgpl or bsd  alternative let med know

**Comment by oroulet** [comment]
btw there is an alternative now: https://gitlab.com/kurant-open/m3d which is almost a drop in
