### ISSUE TITLE
movep function is not working right

### ISSUE THREAD

**Issue by dominotasi** [SintefManufacturing/python-urx#55]
Hi, I and my friends are working on a project with your bibliothek. Our robot is UR3 with OnRobot RG2 Gripper. We want to move the robot's arm to some pose (coordinate), but the movep function is not working and movep function's def  is not the same with UR Script. For Example, even your example code fails. :( I think still this bibliothek is being developed by you.  When this bibliothek will be done? Or can you help us this problem?

**Comment by oroulet** [comment]
I do not have that robot anymore, but you can have a look at code, it is not complicated. As far as I remember we just just send movep command line to robot, so if it is not working with your robot it is something special with your configuration or you have a very robot firmware where UR made som incompatible changes. Another possibility is that a recent PR broke something, but that would be surprising

**Comment by dominotasi** [comment]
Okay, I will be look the code as soon as possible and I think we can run the code tomorrow. We will try your  suggestions. Thanks a lot.
