### ISSUE TITLE
Goal not reached but no program has been running for 5 seconds.

### ISSUE THREAD

**Issue by kaixin-bai** [SintefManufacturing/python-urx#77]
i'm using ur5 now, with 'movej' it works most of the time, but the error below occurs sometimes. 
I found that someone says changing the settings remote control to enable will help for ur e-serie, while i can't find that setting with ur5. Can anyone help me? Thanks! 
 `raise RobotException("Goal not reached but no program has been running for {} seconds. dist is {}, threshold is {}, target is {}, current pose is {}".format(timeout, dist, threshold, target, URRobot.getl(self)))
urx.urrobot.RobotException: Goal not reached but no program has been running for 5 seconds. dist is 1.08735961347, threshold is 0.870018245315, target is [ 3.03882384 -1.97228843  1.8254056  -1.37555343 -1.61774379  1.10942733], current pose is [0.2802325137473805, 0.15454954432829898, -0.10841777566869056, -0.22737147091710713, 3.1121640387628653, 0.021905580945764575]
`

**Comment by kaixin-bai** [comment]
https://github.com/SintefManufacturing/python-urx/issues/62

**Comment by majunqiao** [comment]
hello，I have a same question，How did you solve it
